services:
    apache-php:
        platform: ${OS_PLATFORM}
        image: php:${PHP_VERSION:-7.4}-apache
        container_name: ${COMPOSE_PROJECT_NAME}-web
        restart: unless-stopped
        environment:
            APACHE_DOCUMENT_ROOT: ${APACHE_WEBROOT:-/var/www}
            #- APACHE_RUN_USER=${APACHE_USER:-www-data} # Causes issues with Session-Handling in /tmp
            #- APACHE_RUN_GROUP=${APACHE_GROUP:-www-data} # And causes issues with reading from ../.git
            XDEBUG_CONFIG: >
                mode=${XDEBUG_MODES:-develop,debug}
                idekey=docker
                client_port=${XDEBUG_PORT:-9003}
                client_host=host.docker.internal
                discover_client_host=true
                start_with_request=yes
                trigger_value=StartProfileForMe
                log=/dev/stdout
                log_level=${XDEBUG_LOGLEVEL:-0}
        hostname: webserver
        domainname: ${DOMAINNAME}
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - ${HTTP_PORT:-80}:80
            - ${HTTPS_PORT:-443}:443
        expose:
            - ${HTTP_PORT:-80}
            - ${HTTPS_PORT:-443}
            #- ${XDEBUG_PORT:-9003} # XDebug
        healthcheck:
            test: git --version || exit 1
            interval: 20s
            timeout: 2s
            retries: 10
        volumes:
            - ./Docker/ssl:/etc/apache2/ssl
            - ./Docker/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./Docker/apache2/ssl-default.conf:/etc/apache2/sites-available/default-ssl.conf
            - ./Docker/sendmail/msmtprc:/etc/apache2/sites-available/default-ssl.conf
            - ./.env:${APACHE_WEBROOT:?err}/.env
            - ./.git:${APACHE_WEBROOT:?err}/.git
            - ./cron:${APACHE_WEBROOT:?err}/cron
            - ./data:${APACHE_WEBROOT:?err}/data
            - ./irclogs:${APACHE_WEBROOT:?err}/irclogs
            - ./keys:${APACHE_WEBROOT:?err}/keys
            - ./migration:${APACHE_WEBROOT:?err}/migration
            - ./scripts:${APACHE_WEBROOT:?err}/scripts
            - ./vendor:${APACHE_WEBROOT:?err}/vendor
            - ./www:${APACHE_WEBROOT:?err}/html
        entrypoint: ["/bin/sh","-c"]
        command:
            - |
                a2enmod ssl
                a2ensite default-ssl
                a2enmod rewrite
                cp "${PHP_INI_DIR:?/usr/local/etc/php}/php.ini-development" "${PHP_INI_DIR:?/usr/local/etc/php}/php.ini"
                curl -sSLf \
                   -o /usr/local/bin/install-php-extensions \
                   https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions && \
                chmod +x /usr/local/bin/install-php-extensions && \
                install-php-extensions mysqli pdo_mysql xdebug gd exif
                apt-get -y update && apt-get -y install git msmtp mailutils
                git config --global safe.directory '*'
                grep -Fx -q 'Mutex posixsem' /etc/apache2/apache2.conf || echo 'Mutex posixsem' >> /etc/apache2/apache2.conf
                exec /usr/sbin/apache2ctl -D FOREGROUND
               # Additional install-php-extensions: intl, mbstring, gettext, curl, json, zip, exif

    db:
        platform: ${OS_PLATFORM}
        image: mysql:${MYSQL_VERSION:-5.7}
        container_name: ${COMPOSE_PROJECT_NAME}-db
        restart: unless-stopped
        hostname: database
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-dbpass}
            - MYSQL_DATABASE=${MYSQL_DATABASE?-zooomclan}
            #- MYSQL_USER=${MYSQL_USER-dbuser}
            #- MYSQL_PASSWORD=${MYSQL_PASSWORD-root}
            #- MYSQL_ROOT_HOST="%" # in some scenarios this revokes Host IP connection restrictions
        ports:
            - ${MYSQL_PORT:-3306}:3306
        expose:
            - 3306
        healthcheck:
            test: mysql ${MYSQL_DATABASE} --user=${MYSQL_USER-root} --password='${MYSQL_PASSWORD-root}' --silent --execute "SELECT 1;"
            interval: 10s
            timeout: 3s
            retries: 5
        volumes:
            - ./Docker/mysql57:/var/lib/mysql
        command: [mysqld, --default-authentication-plugin=mysql_native_password, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb_monitor_enable=all, --max-connections=1001, --explicit_defaults_for_timestamp]

    db-manager:
        image: phpmyadmin:latest
        container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
        restart: unless-stopped
        hostname: dbmanager
        depends_on:
            db:
                condition: service_healthy
        environment:
            - PMA_ARBITRARY=1
            #- PMA_HOST=db
            #- MYSQL_USER={MYSQL_USER-root} # phpMyAdmin connects using the MySQL credentials env
            #- MYSQL_PASSWORD=${MYSQL_PASSWORD-root} # phpMyAdmin connects using the MySQL credentials env
        ports:
            - ${PHPMYADMIN_PORT:-8080}:80
