networks:
    frontend:
        driver: bridge

services:
    apache-php:
        platform: ${OS_PLATFORM}
        image: php:${PHP_VERSION:-7.4}-apache
        container_name: ${COMPOSE_PROJECT_NAME}-web
        restart: unless-stopped
        environment:
            - APACHE_DOCUMENT_ROOT=${APACHE_WEBROOT:-/var/www}
            #- APACHE_RUN_USER=${APACHE_USER:-www-data} # Causes issues with Session-Handling in /tmp
            #- APACHE_RUN_GROUP=${APACHE_GROUP:-www-data} # And causes issues with reading from ../.git
        hostname: webserver
        domainname: ${DOMAINNAME}
        networks:
            - frontend
        ports:
            - ${HTTP_PORT:-80}:80
            - ${HTTPS_PORT:-443}:443
        expose:
            - 80
            - 443
        healthcheck:
            test: git --version || exit 1
            interval: 20s
            timeout: 2s
            retries: 10
        volumes:
            - ./Docker/ssl:/etc/apache2/ssl
            - ./Docker/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./Docker/apache2/ssl-default.conf:/etc/apache2/sites-available/default-ssl.conf
            - ./Docker/sendmail/msmtprc:/etc/apache2/sites-available/default-ssl.conf
            - ./.env:${APACHE_WEBROOT:?err}/.env
            - ./.git:${APACHE_WEBROOT:?err}/.git
            #- web-root-git-sync:${APACHE_WEBROOT:?err}/.git:nocopy
            - ./cron:${APACHE_WEBROOT:?err}/cron
            - ./data:${APACHE_WEBROOT:?err}/data
            #- web-root-data-sync:${APACHE_WEBROOT:?err}/data:nocopy Issue with modified Files not being synced
            - ./irclogs:${APACHE_WEBROOT:?err}/irclogs
            - ./keys:${APACHE_WEBROOT:?err}/keys
            - ./migration:${APACHE_WEBROOT:?err}/migration
            - ./scripts:${APACHE_WEBROOT:?err}/scripts
            - web-root-vendor-sync:${APACHE_WEBROOT:?err}/vendor:nocopy
            - ./www:${APACHE_WEBROOT:?err}/html
            #- web-root-www-sync:${APACHE_WEBROOT:?err}/html:nocopy Issue with modified Files not being synced
        entrypoint: ["/bin/sh","-c"]
        command:
            - |
                a2enmod ssl
                a2ensite default-ssl
                a2enmod rewrite
                cp "${PHP_INI_DIR:?/usr/local/etc/php}/php.ini-development" "${PHP_INI_DIR:?/usr/local/etc/php}/php.ini"
                curl -sSLf \
                   -o /usr/local/bin/install-php-extensions \
                   https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions && \
                chmod +x /usr/local/bin/install-php-extensions && \
                install-php-extensions mysqli pdo_mysql xdebug gd exif
                apt-get -y update && apt-get -y install git msmtp mailutils
                grep -Fx -q 'Mutex posixsem' /etc/apache2/apache2.conf || echo 'Mutex posixsem' >> /etc/apache2/apache2.conf
                exec /usr/sbin/apache2ctl -D FOREGROUND
               # Additional install-php-extensions: intl, mbstring, gettext, curl, json, zip, exif

    db:
        platform: ${OS_PLATFORM}
        image: mysql:${MYSQL_VERSION:-5.7}
        container_name: ${COMPOSE_PROJECT_NAME}-db
        restart: unless-stopped
        hostname: database
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-dbpass}
            - MYSQL_DATABASE=${MYSQL_DATABASE?-zooomclan}
            #- MYSQL_USER=${MYSQL_USER-dbuser}
            #- MYSQL_PASSWORD=${MYSQL_PASSWORD-root}
            #- MYSQL_ROOT_HOST="%" # in some scenarios this revokes Host IP connection restrictions
        networks:
            - frontend
        ports:
            - ${MYSQL_PORT:-3306}:3306
        expose:
            - 3306
        healthcheck:
            test: mysql ${MYSQL_DATABASE} --user=${MYSQL_USER-root} --password='${MYSQL_PASSWORD-root}' --silent --execute "SELECT 1;"
            interval: 10s
            timeout: 3s
            retries: 5
        volumes:
            - db-mysql-sync:/var/lib/mysql:nocopy
        command: [mysqld, --default-authentication-plugin=mysql_native_password, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb_monitor_enable=all, --max-connections=1001, --explicit_defaults_for_timestamp]

    db-manager:
        image: phpmyadmin:latest
        container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
        restart: unless-stopped
        hostname: dbmanager
        depends_on:
            db:
                condition: service_healthy
        environment:
            - PMA_ARBITRARY=1
            #- PMA_HOST=db
            #- MYSQL_USER={MYSQL_USER-root} # phpMyAdmin connects using the MySQL credentials env
            #- MYSQL_PASSWORD=${MYSQL_PASSWORD-root} # phpMyAdmin connects using the MySQL credentials env
        networks:
            - frontend
        ports:
            - ${PHPMYADMIN_PORT:-8080}:80

volumes:
    #web-root-git-sync:
        #external: true
    #web-root-data-sync:
        #external: true
    #web-root-www-sync:
        #external: true
    web-root-vendor-sync:
        external: true
    db-mysql-sync:
        external: true
