networks:
    frontend:
        driver: bridge

services:
    apache-php:
        platform: ${OS_PLATFORM}
        image: php:${PHP_VERSION:-7.4}-apache
        container_name: ${COMPOSE_PROJECT_NAME}-web
        restart: unless-stopped
        environment:
            - APACHE_DOCUMENT_ROOT=${APACHE_WEBROOT:-/var/www}
        hostname: webserver
        domainname: ${DOMAINNAME}
        networks:
            - frontend
        ports:
            - ${HTTP_PORT:-80}:80
            - ${HTTPS_PORT:-443}:443
        expose:
            - 80
            - 443
        healthcheck:
            test: git --version || exit 1
            interval: 20s
            timeout: 2s
            retries: 10
        volumes:
            - ./Docker/ssl:/etc/apache2/ssl
            - ./Docker/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./Docker/apache2/ssl-default.conf:/etc/apache2/sites-available/default-ssl.conf
            - ./.git:${APACHE_WEBROOT:?err}/.git
            - ./cron:${APACHE_WEBROOT:?err}/cron
            - ./data:${APACHE_WEBROOT:?err}/data
            - ./irclogs:${APACHE_WEBROOT:?err}/irclogs
            - ./keys:${APACHE_WEBROOT:?err}/keys
            - ./migration:${APACHE_WEBROOT:?err}/migration
            - ./scripts:${APACHE_WEBROOT:?err}/scripts
            - ./vendor:${APACHE_WEBROOT:?err}/vendor
            - ./www:${APACHE_WEBROOT:?err}/html
        entrypoint: ["/bin/sh","-c"]
        command:
            - |
                echo "Mutex posixsem" >> /etc/apache2/apache2.conf
                a2enmod ssl
                a2ensite default-ssl
                a2enmod rewrite
                curl -sSLf \
                   -o /usr/local/bin/install-php-extensions \
                   https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions && \
                chmod +x /usr/local/bin/install-php-extensions && \
                install-php-extensions mysqli pdo_mysql gd xdebug
                apt-get -y update && apt-get -y install git
                exec /usr/sbin/apache2ctl -D FOREGROUND
               # Additional install-php-extensions: intl, mbstring, gettext, curl, json, zip, exif

    db:
        platform: ${OS_PLATFORM}
        image: mysql:${MYSQL_VERSION:-5.7}
        container_name: ${COMPOSE_PROJECT_NAME}-db
        restart: unless-stopped
        hostname: database
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-dbpass}
            - MYSQL_DATABASE=${MYSQL_DATABASE?-zooomclan}
            #- MYSQL_USER=${MYSQL_USER:-dbuser}
            #- MYSQL_PASSWORD=${MYSQL_PASSWORD:-root}
            #- MYSQL_ROOT_HOST="%" # in some scenarios this revokes Host IP connection restrictions
        networks:
            - frontend
        ports:
            - ${MYSQL_PORT:-3306}:3306
        expose:
            - 3306
        healthcheck:
            test: mysql ${MYSQL_DATABASE} --user=${MYSQL_USER} --password='${MYSQL_PASSWORD}' --silent --execute "SELECT 1;"
            interval: 10s
            timeout: 3s
            retries: 5
        volumes:
            - ${MYSQL_LOCAL_DATABASE_PATH:-./Docker/mysql57}:/var/lib/mysql
        command: [mysqld, --default-authentication-plugin=mysql_native_password, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb_monitor_enable=all, --max-connections=1001, --explicit_defaults_for_timestamp]

    db-manager:
        image: phpmyadmin:latest
        container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
        restart: unless-stopped
        hostname: dbmanager
        depends_on:
            db:
                condition: service_healthy
        environment:
            - PMA_ARBITRARY=1
            #- PMA_HOST=db
            #- MYSQL_USER={MYSQL_USER:-root} # phpMyAdmin connects using the MySQL credentials env
            #- MYSQL_PASSWORD=${MYSQL_PASSWORD:-root} # phpMyAdmin connects using the MySQL credentials env
        networks:
            - frontend
        ports:
            - ${PHPMYADMIN_PORT:-8080}:80

